import contextlib
import hashlib
import io
import json
import shutil
import tempfile
import textwrap
import unittest
from pathlib import Path

from tools.recover_test_argv import main

FIXTURE_JSON = Path(__file__).parent / "fixtures" / "mini" / "problem.json"

# Prints its arguments, one per line — a pure function of argv.
GEN_ECHO = r"""
#include <cstdio>
int main(int argc, char **argv) {
    for (int i = 1; i < argc; ++i) std::printf("%s\n", argv[i]);
    return 0;
}
"""

# Different bytes on every run.
GEN_NOISE = r"""
#include <cstdio>
#include <unistd.h>
int main() { std::printf("%d\n", (int)getpid()); return 0; }
"""

SCRIPT_HEAD = """\
#!/usr/bin/env bash
set -eu
cd "$(dirname "${BASH_SOURCE[0]}")"
GROUP=tests/g1
mkdir -p bin "$GROUP"
rm -f "$GROUP"/*.in
g++ -O2 -o bin/gen-echo files/gen-echo.cpp
idx=0
CUR=""
next() { idx=$((idx + 1)); CUR=$(printf "%s/%02d.in" "$GROUP" "$idx"); }
gen() { next; ./bin/"$@" > "$CUR"; }
"""

MAIN_BODY = """\
for s in 1 2 3; do
    gen gen-echo "$s" --shape=star
done
next; printf '5 5\\n' > "$CUR"
next; cat > "$CUR" <<'EOF'
hand made
EOF
gen gen-echo 7 --n=10
gen gen-echo "a b"
next; ./bin/gen-echo 9 | tr 9 8 > "$CUR"
gen gen-echo 10 --x
echo extra >> "$CUR"
gen gen-echo 11 --first
./bin/gen-echo 11 --second > "$CUR"
"""


def _tree_hash(root: Path) -> str:
    h = hashlib.sha256()
    for p in sorted(root.rglob("*")):
        h.update(str(p.relative_to(root)).encode())
        if p.is_file():
            h.update(p.read_bytes())
    return h.hexdigest()


@unittest.skipUnless(shutil.which("g++"), "g++ not found")
class TestRecoverTestArgv(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.problem = self.tmp / "problem"
        self.out = self.tmp / "out"

    def tearDown(self):
        self._tmp.cleanup()

    def make_package(self, body: str, extra_gens: dict[str, str] | None = None,
                     build: bool = True):
        files = self.problem / "files"
        files.mkdir(parents=True)
        shutil.copy(FIXTURE_JSON, self.problem / "problem.json")
        (files / "gen-echo.cpp").write_text(GEN_ECHO)
        compile_lines = ""
        for name, src in (extra_gens or {}).items():
            (files / f"{name}.cpp").write_text(src)
            compile_lines += f"g++ -O2 -o bin/{name} files/{name}.cpp\n"
        (self.problem / "build_tests.sh").write_text(
            SCRIPT_HEAD + compile_lines + textwrap.dedent(body))
        if build:
            import subprocess
            subprocess.run(["bash", "build_tests.sh"], cwd=self.problem,
                           check=True, capture_output=True)
            # The tool must not depend on the package's own build products.
            shutil.rmtree(self.problem / "bin")

    def run_main(self, *extra):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = main(["recover_test_argv", str(self.problem), str(self.out),
                         *extra])
        return code, out.getvalue(), err.getvalue()

    def manifest(self):
        return json.loads((self.out / "tests-manifest.json").read_text())

    def test_recovers_gen_and_manual_tests(self):
        self.make_package(MAIN_BODY)
        before = _tree_hash(self.problem)
        code, out, err = self.run_main("--offset", "100")
        self.assertEqual(code, 0, out + err)
        self.assertEqual(_tree_hash(self.problem), before)

        m = self.manifest()
        self.assertEqual(m["schema"], 1)
        self.assertEqual(m["problem"], str(self.problem.resolve()))
        self.assertEqual(m["generators"], ["gen-echo"])
        tests = m["tests"]
        self.assertEqual([t["index"] for t in tests], list(range(1, 11)))
        self.assertEqual(tests[0], {"index": 1, "group": "g1",
                                    "file": "tests/g1/01.in", "kind": "gen",
                                    "generator": "gen-echo",
                                    "args": ["1", "--shape=star"]})
        self.assertEqual(tests[2]["args"], ["3", "--shape=star"])
        reasons = {t["index"]: t.get("reason") for t in tests}
        self.assertEqual(reasons[4], "no generator wrote it")       # printf
        self.assertEqual(reasons[5], "no generator wrote it")       # heredoc
        self.assertEqual(tests[5]["kind"], "gen")
        self.assertEqual(reasons[7], "argv not expressible in a Polygon script")
        self.assertEqual(reasons[8], "no generator wrote it")       # pipe
        self.assertEqual(reasons[9], "regenerated bytes differ")    # appended
        # Two generator calls into one file: the last one wins.
        self.assertEqual(tests[9]["kind"], "gen")
        self.assertEqual(tests[9]["args"], ["11", "--second"])

        script = (self.out / "script.txt").read_text()
        self.assertEqual(script.splitlines(), [
            "gen-echo 1 --shape=star > 101",
            "gen-echo 2 --shape=star > 102",
            "gen-echo 3 --shape=star > 103",
            "gen-echo 7 --n=10 > 106",
            "gen-echo 11 --second > 110",
        ])
        self.assertNotIn("#", script)
        self.assertIn("5 gen, 5 manual", out)

    def test_no_script_txt_without_offset(self):
        self.make_package("gen gen-echo 1\n")
        code, _, _ = self.run_main()
        self.assertEqual(code, 0)
        self.assertFalse((self.out / "script.txt").exists())

    def test_groups_follow_problem_json_and_numeric_order(self):
        self.make_package("gen gen-echo 1\n")
        data = json.loads((self.problem / "problem.json").read_text())
        data["subtasks"] = [
            {"id": "zz", "points": 40, "bounds": {}, "constraints_text": [], "depends_on": []},
            {"id": "g1", "points": 60, "bounds": {}, "constraints_text": [], "depends_on": []},
        ]
        (self.problem / "problem.json").write_text(json.dumps(data))
        with open(self.problem / "build_tests.sh", "a") as fh:
            fh.write("mkdir -p tests/zz\nfor i in 10 9; do "
                     "./bin/gen-echo z$i > tests/zz/$i.in; done\n")
        (self.problem / "tests" / "zz").mkdir()
        for i in (10, 9):
            (self.problem / "tests" / "zz" / f"{i}.in").write_text(f"z{i}\n")
        code, out, err = self.run_main()
        self.assertEqual(code, 0, out + err)
        files = [(t["index"], t["file"]) for t in self.manifest()["tests"]]
        self.assertEqual(files, [(1, "tests/zz/9.in"), (2, "tests/zz/10.in"),
                                 (3, "tests/g1/01.in")])

    def test_nondeterministic_generator_is_manual_and_exit_1(self):
        self.make_package("gen gen-echo 1\ngen gen-noise 2\n",
                          extra_gens={"gen-noise": GEN_NOISE})
        code, out, err = self.run_main()
        self.assertEqual(code, 1)
        tests = self.manifest()["tests"]
        self.assertEqual(tests[0]["kind"], "gen")
        self.assertEqual(tests[1]["reason"], "nondeterministic")
        self.assertIn("tests/g1/02.in", err)

    def test_unreproducible_manual_test_exit_1(self):
        self.make_package('next; echo "$RANDOM$RANDOM" > "$CUR"\n')
        code, _, err = self.run_main()
        self.assertEqual(code, 1)
        self.assertTrue((self.out / "tests-manifest.json").exists())
        self.assertIn("rebuilt bytes differ", err)

    def test_failing_script_exit_2(self):
        self.make_package("gen gen-echo 1\n")
        with open(self.problem / "build_tests.sh", "a") as fh:
            fh.write("echo boom >&2; exit 3\n")
        code, _, err = self.run_main()
        self.assertEqual(code, 2)
        self.assertIn("boom", err)

    def test_missing_script_exit_2(self):
        self.make_package("gen gen-echo 1\n")
        (self.problem / "build_tests.sh").unlink()
        code, _, err = self.run_main()
        self.assertEqual(code, 2)
        self.assertIn("no such build script", err)

    def test_missing_tests_exit_2(self):
        self.make_package("gen gen-echo 1\n", build=False)
        code, _, _ = self.run_main()
        self.assertEqual(code, 2)

    def test_out_dir_inside_problem_dir_exit_2(self):
        self.make_package("gen gen-echo 1\n")
        self.out = self.problem / "out"
        code, _, err = self.run_main()
        self.assertEqual(code, 2)
        self.assertFalse(self.out.exists())

    def test_usage_error_exit_2(self):
        with contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(main(["recover_test_argv"]), 2)


if __name__ == "__main__":
    unittest.main()
